config/routes.rb
Rails.application.routes.draw do

  resources :todos do
    collection do
      get :v1
      get :v2
      get :v3
    end
  end

  get 'this' => "welcome#this"

  post 'pay2go/return'
  post 'pay2go/notify'

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do

    post "/login" => "auth#login"
    post "/logout" => "auth#logout"

    resources :topics
  end

  resources :products do
    member do
      post :buy
      post :cancel
    end
  end

  resources :orders do
    member do
      post :checkout_pay2go
    end
  end

  resources :people
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/ajax" => "welcome#ajax"
  get "/ajaxtest" => "welcome#ajaxtest"

  get "/ubike" => "welcome#ubike"

  resources :users

  resources :topics do
    resources :comments
    resources :likes

    member do
      post :subscribe
      post :unsubscribe
    end
  end

  namespace :admin do
    resources :orders
  end

  root 'topics#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates_presence_of :content
  
  belongs_to :user
  belongs_to :topic

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_topic

  def create
    @comment = @topic.comments.new( comment_params )
    @comment.user = current_user

    if @comment.save

      # notify users
      all_users = @topic.comments.map{ |c| c.user }
      all_users << @topic.user
      all_users = all_users.uniq
      all_users.each do |u|
        UserMailer.notify_comment(@topic, u).deliver_later
      end

      respond_to do |format|
        format.html { redirect_to topic_url(@topic) }
        format.js # create.js.erb
      end

    else
      respond_to do |format|
        format.html { render "topics/show" }
        format.js # create.js.erb
      end
    end
  end

  def destroy
    @comment = current_user.comments.find( params[:id] )
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.js # destroy.js.erb
    end
  end

  protected

  def set_topic
    @topic = Topic.find( params[:topic_id] )
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li id="comment-<%= c.id %>"><%= c.content %> by <%= c.user.try(:display_name) %>

  <% if current_user && c.user == current_user %>
    (<%= link_to "Delete", topic_comment_path(@topic, c), :method => :delete, :remote => true %>)
  <% end %>

</li>

app/views/comments/create.js.erb
<% if @comment.valid? %>

  $("#comments-list").prepend("<%=j render( :partial => "comment", :locals => { :c => @comment }  ) %>");
  $("#new_comment").trigger('reset');

<% else %>

  alert("新增失敗!!!");
  
<% end %>

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();
//alert("刪除成功!");