config/routes.rb
Rails.application.routes.draw do

  resources :todos do
    collection do
      get :v1
      get :v2
      get :v3
    end
  end

  get 'this' => "welcome#this"

  post 'pay2go/return'
  post 'pay2go/notify'

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do

    post "/login" => "auth#login"
    post "/logout" => "auth#logout"

    resources :topics
  end

  resources :products do
    member do
      post :buy
      post :cancel
    end
  end

  resources :orders do
    member do
      post :checkout_pay2go
    end
  end

  resources :people
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/ajax" => "welcome#ajax"
  get "/ajaxtest" => "welcome#ajaxtest"

  get "/ubike" => "welcome#ubike"

  resources :users

  resources :topics do
    resources :comments
    resources :likes

    member do
      post :subscribe
      post :unsubscribe
    end
  end

  namespace :admin do
    resources :orders
  end

  root 'topics#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base

  STATUS = ["draft", "published", "scheduled"]

  validates_presence_of :subject

  belongs_to :user
  belongs_to :category

  has_many :comments

  has_many :likes
  has_many :like_users, :through => :likes, :source => :user

  has_many :subscriptions
  has_many :subscribed_users, :through => :likes, :source => :user

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png",
                    :storage => :s3, :s3_credentials => "#{Rails.root}/config/s3.yml", :s3_host_name => "s3-ap-northeast-1.amazonaws.com"

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def finy_like_by(user)
    user && self.likes.find_by_user_id( user.id )
  end

  def finy_subscription_by(user)
    user && self.subscriptions.find_by_user_id( user.id )
  end

end

app/controllers/api_v1/topics_controller.rb
class ApiV1::TopicsController < ApiController

  def index
    @topics = Topic.page( params[:page] )
  end

  def show
    @topic = Topic.find(params[:id])
    # show.json.jbuilder
  end

  def create
    @topic = Topic.new( :subject => params[:subject],
                        :content => params[:content] )

    if @topic.save
      render :json => { :id => @topic.id }
    else
      render :json => { :message => "failed", :errors => @topic.errors }, :status => 400
    end
  end

  def update
    @topic = Topic.find( params[:id] )

    columns = [:subject, :content]

    #if params.slice(*columns).keys.any?
    if columns.any?{ |c| params.key?(c) }
      columns.each do |column|
        @topic[column] = params[column] if params[column]
      end

      if @topic.save
        render :json => { :id => @topic.id }
      else
        render :json => { :message => "failed", :errors => @topic.errors }, :status => 400
      end

    else
      render :json => { :message => "no keys"}, :status => 400
    end
  end

  def destroy
    @topic = Topic.find( params[:id] )
    @topic.destroy

    render :json => { :message => "OK" }
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_my_topic, :only => [:edit, :update, :destroy]

  def index
    @q = Topic.ransack(params[:q])
    @topics = @q.result(distinct: true)

    if params[:sort] == "id"
      @topics = @topics.order("id")
    elsif params[:sort] == "updated"
      @topics = @topics.order("updated_at DESC")
    else
      @topics = @topics.order("id DESC")
    end

    @topics = @topics.where( :status => "published" )

    @topics = @topics.page( params[:page] )
  end

  def show
    @topic = Topic.find( params[:id] )
    @comment = Comment.new

    respond_to do |format|
      format.html
      format.json {
        render :json => { :id => @topic.id, :subject => @topic.subject }
      }
    end
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new( topic_params )
    @topic.user = current_user

    if @topic.save
      redirect_to topic_url(@topic)
    else
      render :new
    end
  end

  def edit
      end

  def update

    if params[:destory_image]
      @topic.image = nil
    end

    if @topic.update( topic_params )
      redirect_to topic_url(@topic)
    else
      render "edit"
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_url
  end

  def subscribe
    @topic = Topic.find( params[:id] )

    subscription = @topic.finy_subscription_by(current_user)
    if subscription
      # do nothing
    else
      @subscription = @topic.subscriptions.create!( :user => current_user )
    end

    redirect_to :back
  end

  def unsubscribe
    @topic = Topic.find( params[:id] )

    subscription = @topic.finy_subscription_by(current_user)
    subscription.destroy

    redirect_to :back
  end

  protected

  def topic_params
    params.require(:topic).permit(:content, :subject, :image, :category_id, :status)
  end

  def set_my_topic
    @topic = current_user.topics.find( params[:id])
  end

end

app/helpers/topics_helper.rb
module TopicsHelper

  def topic_status_options

    Topic::STATUS.map do |status|
      [ t(status, :scope => "topic.status"), status ]
    end

  end

  def category_name_options
    Category.all.map do |c|
      [ c.name, c.id ]
    end
  end

end

app/views/topics/_form.html.erb
<% if @topic.errors.any? %>
   <% @topic.errors.full_messages.each do |m| %>
   <p><%= m %></p>
   <% end %>
<% end %>

<%= form_for @topic do |f| %>

  <div class="form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :status %>
    <%= f.select :status, topic_status_options, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%#= f.collection_select :category_id, Category.all, :id, :name, {}, :class => "form-control" %>
    <%= f.select :category_id, category_name_options, {}, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, :class => "form-control" %>

    <% if @topic.image.exists? %>
      <%= check_box_tag "destory_image", "1" %> 刪除圖片
    <% end %>

  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>

<% end %>

<script>

  $( "#topic_category_id" ).select2({
    theme: "bootstrap"
  });

</script>

app/views/topics/_like.html.erb
<h2><%= @topic.likes.count %></h2>
<% if like %>
  <%= link_to "Unlike", topic_like_path(@topic, like), :remote => true, :method => :delete, :class => "btn btn-primary btn-lg" %>
<% else %>
  <%= link_to "Like", topic_likes_path(@topic), :remote => true, :method => :post, :class => "btn btn-primary btn-lg" %>
<% end %>

app/views/topics/edit.html.erb
<%= render "form" %>

app/views/topics/index.html.erb
<div id="example">
  <app></app>
</div>

<script>
  new Vue({
   el: '#example'
  })
</script>

<p>
  <%= link_to "New Topic", new_topic_path, :class => "btn btn-primary" %>
</p>

<%= search_form_for @q do |f| %>
  <%= f.label :subject_cont %>
  <%= f.search_field :subject_cont %>
  <%= f.submit "Search" %>
<% end %>

<p>
  <%= sort_link(@q, :id) %>
  <%= sort_link(@q, :updated_at, "最後更新時間") %>
</p>

<table class="table">
  <% @topics.each do |p| %>
  <tr>
    <td><%= link_to p.subject, topic_path(p) %></td>
    <td><%= p.user.try(:display_name) %></td>
    <td><%= p.created_at.to_s(:short) %></td>
    <td>
      <% if current_user && ( p.user == current_user ) %>
        <%= link_to "Edit", edit_topic_path(p), :class => "btn btn-default btn-sm" %>
        <%= link_to "Delete", topic_path(p), :data => { :confirm => "r u sure?"}, :class => "btn btn-danger btn-sm", :method => :delete %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>

<%= paginate @topics %>

app/views/topics/new.html.erb
<% if @topic.errors.any? %>
   <% @topic.errors.full_messages.each do |m| %>
   <p><%= m %></p>
   <% end %>
<% end %>

<%= form_for @topic do |f| %>

  <div class="form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, :class => "form-control" %>
  </div>


  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>

<% end %>

app/views/topics/show.html.erb
<h1><%= @topic.subject %></h1>

<% like = @topic.finy_like_by(current_user) %>

<div id="like-area">
  <%= render :partial => "like", :locals => { :like => like } %>
</div>


<% subscription = @topic.finy_subscription_by(current_user) %>
<% if subscription %>
  <%= link_to "Unsubscribe", unsubscribe_topic_path(@topic), :method => :post, :class => "btn btn-primary btn-lg" %>
<% else %>
  <%= link_to "Subscribe", subscribe_topic_path(@topic), :method => :post, :class => "btn btn-primary btn-lg" %>
<% end %>


<% if @topic.image.exists? %>
  <%= link_to @topic.image.url, :target => "_blank" do %>
    <%= image_tag(@topic.image.url(:thumb)) %>
  <% end %>
<% end %>

<h2>Status: <%= t( @topic.status, :scope => "topic.status" ) %></h2>

<h2>Category: <%= @topic.category.try(:name) %></h2>

<%= simple_format @topic.content %>

<%= form_for [@topic, @comment], :remote => true do |f| %>

  <% if @comment.errors.any? %>
     <% @comment.errors.full_messages.each do |m| %>
     <p><%= m %></p>
     <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-warning" %>
  </div>
<% end %>

<h2>Comment list</h2>

<ul id="comments-list">
<% @topic.comments.order("id DESC").each do |c| %>
  <%= render :partial => "comments/comment", :locals => { :c => c } %>
<% end %>
</ul>